# Generated by Django 4.0 on 2024-06-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstorePickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(choices=[('Nam', 'Namibia'), ('SA', 'South Africa'), ('Zim', 'Zimbabwe')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='pickup_instore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.instorepickuppoint'),
        ),
    ]
