# Generated by Django 5.0.6 on 2024-06-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_status_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paynow_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
