# Generated by Django 4.0 on 2024-06-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('F', 'Formal'), ('C', 'Casual'), ('S', 'Sports'), ('SH', 'Shoes')], default='F', max_length=2)),
            ],
            options={
                'verbose_name': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('name', models.CharField(choices=[('F', 'Formal'), ('C', 'Casual'), ('S', 'Sports'), ('SH', 'Shoes')], default='F', max_length=2)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('size', models.ManyToManyField(to='products.Size')),
            ],
        ),
    ]
